"""M1: verify d(loss)/d(wind_strength) through the rollout against finite differences.

Target trajectory is generated by the same solver with a different (known) wind
strength theta_true; the loss is trajectory MSE. The analytic gradient comes from
wp.Tape through the full rollout; it is compared to central finite differences
at several step sizes.

Usage: python scripts/check_grad.py [--solver semi_implicit|vbd] [--theta0 12] [--theta-true 18]
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import warp as wp  # noqa: E402

from src.motion.loss import TrajectoryLoss  # noqa: E402
from src.sim.rollout import FlagSim  # noqa: E402


def make_target(cfg, theta_true):
    cfg_t = yaml.safe_load(yaml.safe_dump(cfg))  # deep copy
    cfg_t["wind"]["strength"] = float(theta_true)
    sim = FlagSim(cfg_t, requires_grad=False)
    sim.rollout()
    return sim.trajectory()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(REPO / "configs" / "flag.yaml"))
    ap.add_argument("--solver", default=None)
    ap.add_argument("--theta0", type=float, default=12.0, help="evaluation point")
    ap.add_argument("--theta-true", type=float, default=18.0, help="target wind strength")
    args = ap.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    if args.solver:
        cfg["sim"]["solver"] = args.solver
    np.random.seed(cfg["seed"])

    wp.init()
    assert wp.get_device(cfg["device"]).is_cuda, "requires a GPU"

    with wp.ScopedDevice(cfg["device"]):
        solver_name = cfg["sim"]["solver"]
        print(f"solver={solver_name}  theta_true={args.theta_true}  theta0={args.theta0}")

        print("generating synthetic target ...")
        target = make_target(cfg, args.theta_true)

        # --- analytic gradient via tape -----------------------------------
        cfg_e = yaml.safe_load(yaml.safe_dump(cfg))
        cfg_e["wind"]["strength"] = args.theta0
        sim = FlagSim(cfg_e, requires_grad=True)
        loss_mod = TrajectoryLoss(target, requires_grad=True)

        t0 = time.time()
        tape = wp.Tape()
        with tape:
            sim.rollout()
            loss_mod.compute(sim.frame_states())
        loss_val = loss_mod.value()
        tape.backward(loss_mod.loss)
        wp.synchronize()
        grad = float(sim.wind_strength.grad.numpy()[0])
        t_tape = time.time() - t0
        tape.zero()
        print(f"L(theta0) = {loss_val:.8e}")
        print(f"tape gradient dL/dtheta = {grad:+.8e}   ({t_tape:.1f} s fwd+bwd)")

        # --- finite differences -------------------------------------------
        fd_sim = FlagSim(cfg_e, requires_grad=False)
        fd_loss = TrajectoryLoss(target, requires_grad=False)

        def loss_at(theta):
            fd_sim.set_wind_strength(theta)
            fd_sim.rollout()
            fd_loss.compute(fd_sim.frame_states())
            return fd_loss.value()

        print(f"{'h':>8}  {'FD central':>16}  {'rel err vs tape':>16}")
        results = []
        for h in [1.0, 0.3, 0.1, 0.03]:
            fd = (loss_at(args.theta0 + h) - loss_at(args.theta0 - h)) / (2 * h)
            rel = abs(fd - grad) / max(abs(fd), abs(grad), 1e-12)
            results.append((h, fd, rel))
            print(f"{h:8.3f}  {fd:+16.8e}  {rel:16.3e}")

        best_rel = min(r[2] for r in results)
        ok = best_rel < 0.02 and abs(grad) > 0.0
        print()
        if ok:
            print(f"GRADIENT CHECK PASSED for {solver_name}: best rel err {best_rel:.3e}")
        else:
            print(
                f"GRADIENT CHECK FAILED for {solver_name}: best rel err {best_rel:.3e}, "
                f"tape grad {grad:+.3e} -> use CEM fallback (scripts/recover_synthetic.py --method cem)"
            )
        return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
