"""The probe->parameter matrix, run on REAL Cosmos3-generated video.

Three probes of the same real scene (two balls on the wooden table), each generated by
the Cosmos3 world model from its own initial frame + prompt:

    drop     — the red ball falls onto the table
    push     — the red ball rolls across the table and slows
    collide  — the red ball rolls into the blue ball and knocks it away

We track both balls, then fit a two-ball rigid sim (ground + ball-ball penalty contact,
Coulomb friction) whose camera-projected centres must match the tracked ones. The
launch velocity of the red ball is a nuisance parameter (Cosmos chose it, we don't know
it) and is re-fitted at every point of the scan.

There is NO ground truth here — the video was dreamed up — so instead of a recovery
error we report, per (probe, parameter), the CONFIDENCE INTERVAL implied by the fit:
scan the parameter, re-fit the nuisance velocity, and keep the values whose fit stays
within the tracking-noise margin of the best. A parameter whose whole prior range fits
equally well is not identified by that probe.

Run: CUDA_VISIBLE_DEVICES=<g> python scripts/cosmos_matrix.py   (warp env)
"""
import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import warp as wp  # noqa: E402

from src.render.camera import Camera  # noqa: E402
from src.sim.probe_scene import ProbeScene  # noqa: E402
from src.track.balls import track_balls  # noqa: E402

OUT = REPO / "outputs" / "probes_i2v"
CHOSEN = {"drop": 0, "push": 3, "collide": 2}      # most physical take per probe
# collide seed 2 is the only CAUSAL knock: the balls are actually touching (-3 px surface
# gap) at the frame blue starts moving. In other seeds blue accelerates on its own.
FPS, SUB = 24, 40
NOISE_PX = 2.5                                      # tracking-noise margin
NOMINAL = {"cd": 12.0, "mu": 0.35, "ratio": 1.0}
PARAMS = [("cd", "Restitution", (3.0, 80.0), True),
          ("mu", "Friction", (0.05, 1.2), False),
          ("ratio", "Mass ratio", (0.25, 4.0), True)]
# Cosmos rolls the balls toward the camera as well as sideways, so v0y must be allowed
# to be large and NEGATIVE (-y is toward the camera in this scene)
V0_GRID = {"drop": (np.linspace(-0.4, 0.4, 5), np.linspace(-0.5, 0.5, 5)),
           "push": (np.linspace(0.0, 1.8, 7), np.linspace(-0.9, 0.5, 7)),
           "collide": (np.linspace(0.0, 2.2, 8), np.linspace(-0.9, 0.5, 7))}


def load_tracks(probe):
    fr = np.load(OUT / f"vid_{probe}_seed{CHOSEN[probe]}.npz")["frames"]
    A, RA, B, RB = track_balls(fr)
    return fr, A, B


def simulate(cfg, probe, v0, theta, n_frames):
    L = cfg["layouts"][probe]
    sc = ProbeScene(["A", "B"], [L[0], L[1]], [[float(v0[0]), float(v0[1]), 0.0], [0, 0, 0]],
                    densities=(600.0, 600.0 * theta["ratio"]), ground_z=cfg["ground_z"],
                    dt=1.0 / (FPS * SUB), n_steps=n_frames * SUB, k=40000.0,
                    cd=theta["cd"], mu=theta["mu"], ball_radius=cfg["ball_radius"])
    sc.rollout()
    return sc.positions(SUB)


def rms_error(cfg, cam, probe, v0, theta, A, B, n_frames):
    P = simulate(cfg, probe, v0, theta, n_frames)
    if not np.isfinite(P).all():
        return 1e6
    uvA, _ = cam.project(P[:len(A), 0]); uvB, _ = cam.project(P[:len(B), 1])
    e, n = 0.0, 0
    for uv, T in ((uvA, A), (uvB, B)):
        m = ~np.isnan(T[:, 0])
        if m.sum():
            e += float(((uv[:len(T)][m] - T[m]) ** 2).sum()); n += int(m.sum()) * 2
    return float(np.sqrt(e / max(n, 1)))


def fit_v0(cfg, cam, probe, theta, A, B, nf, centre=None, span=None):
    """Best launch velocity for the red ball under a given theta."""
    if centre is None:
        gx, gy = V0_GRID[probe]
    else:
        gx = centre[0] + span * np.linspace(-1, 1, 3)
        gy = centre[1] + span * np.linspace(-1, 1, 3)
    best = (1e9, (0.0, 0.0))
    for vx in gx:
        for vy in gy:
            r = rms_error(cfg, cam, probe, (vx, vy), theta, A, B, nf)
            if r < best[0]:
                best = (r, (float(vx), float(vy)))
    step = (gx[1] - gx[0]) * 0.5 if len(gx) > 1 else 0.1
    for _ in range(2):                                    # local refine of the nuisance
        cx, cy = best[1]
        for vx in cx + step * np.array([-1.0, 0.0, 1.0]):
            for vy in cy + step * np.array([-1.0, 0.0, 1.0]):
                r = rms_error(cfg, cam, probe, (vx, vy), theta, A, B, nf)
                if r < best[0]:
                    best = (r, (float(vx), float(vy)))
        step *= 0.5
    return best


def main():
    cfg = json.loads((OUT / "scene.json").read_text())
    cam = Camera(cfg["camera"])
    wp.init()
    results = {}
    with wp.ScopedDevice("cuda:0"):
        for probe in CHOSEN:
            fr, A, B = load_tracks(probe)
            nf = len(fr)
            uv0, _ = cam.project(np.array([cfg["layouts"][probe][0]]))
            print(f"\n=== {probe} (seed {CHOSEN[probe]}) === tracked A {np.mean(~np.isnan(A[:,0]))*100:.0f}% "
                  f"B {np.mean(~np.isnan(B[:,0]))*100:.0f}% | frame-0 check: sim {uv0[0].round(0)} vs tracked {A[0].round(0)}")

            base_rms, base_v0 = fit_v0(cfg, cam, probe, dict(NOMINAL), A, B, nf)
            print(f"  baseline fit: v0={np.round(base_v0,2)}  rms={base_rms:.1f} px")

            for key, lab, (lo, hi), logsc in PARAMS:
                scan = np.geomspace(lo, hi, 9) if logsc else np.linspace(lo, hi, 9)
                rmss = []
                for val in scan:
                    th = dict(NOMINAL); th[key] = float(val)
                    r, _ = fit_v0(cfg, cam, probe, th, A, B, nf, centre=base_v0, span=0.18)
                    rmss.append(r)
                rmss = np.array(rmss)
                imin = int(np.argmin(rmss)); rmin = float(rmss[imin])
                ok = rmss <= rmin + NOISE_PX                       # within the noise margin
                # contiguous interval around the minimum
                lo_i = imin
                while lo_i - 1 >= 0 and ok[lo_i - 1]:
                    lo_i -= 1
                hi_i = imin
                while hi_i + 1 < len(scan) and ok[hi_i + 1]:
                    hi_i += 1
                if logsc:
                    frac = np.log(scan[hi_i] / scan[lo_i]) / np.log(hi / lo)
                else:
                    frac = (scan[hi_i] - scan[lo_i]) / (hi - lo)
                spread = float(rmss.max() - rmss.min())
                railed = imin in (0, len(scan) - 1)     # optimum sits outside the prior
                ident = (frac < 0.55) and (spread > NOISE_PX) and not railed
                results[(probe, key)] = dict(scan=scan.tolist(), rms=rmss.tolist(), best=float(scan[imin]),
                                             lo=float(scan[lo_i]), hi=float(scan[hi_i]), frac=float(frac),
                                             spread=spread, identified=bool(ident), rmin=rmin,
                                             railed=bool(railed))
                tag = "IDENTIFIED" if ident else ("railed" if railed else "not identified")
                print(f"  {lab:11s}: {tag:14s} best {scan[imin]:7.2f}  interval [{scan[lo_i]:.2f},{scan[hi_i]:.2f}] "
                      f"= {frac*100:3.0f}% of prior | rms spread {spread:5.1f} px (noise {NOISE_PX})")

    np.savez(OUT / "cosmos_matrix.npz",
             keys=np.array([f"{p}|{k}" for (p, k) in results], dtype=object),
             vals=np.array([json.dumps(v) for v in results.values()], dtype=object))
    print(f"\nwrote {OUT}/cosmos_matrix.npz")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
