"""M1/M2: recover the wind strength theta from a synthetic target trajectory.

The target is generated by the same solver with theta_true (exact ground truth).
Two optimizers:
  --method grad : Adam on the wp.Tape gradient (requires semi_implicit solver;
                  gradients do not flow through VBD as of newton 1.4.0)
  --method cem  : cross-entropy method, zeroth-order (works with any solver)

Prints the loss curve and theta_true vs recovered theta, writes a plot.

Usage: python scripts/recover_synthetic.py [--method grad|cem] [--solver ...] [--theta0 8]
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import warp as wp  # noqa: E402

from src.motion.loss import TrajectoryLoss  # noqa: E402
from src.optimize.cem import cem_1d  # noqa: E402
from src.sim.rollout import FlagSim  # noqa: E402


def make_target(cfg, theta_true):
    cfg_t = yaml.safe_load(yaml.safe_dump(cfg))
    cfg_t["wind"]["strength"] = float(theta_true)
    sim = FlagSim(cfg_t, requires_grad=False)
    sim.rollout()
    return sim.trajectory()


def recover_grad(cfg, target, theta0, iters=40, lr=0.4):
    """Adam on the tape gradient. Returns (theta_hat, history)."""
    cfg_e = yaml.safe_load(yaml.safe_dump(cfg))
    cfg_e["wind"]["strength"] = float(theta0)
    sim = FlagSim(cfg_e, requires_grad=True)
    loss_mod = TrajectoryLoss(target, requires_grad=True)

    m = v = 0.0
    beta1, beta2, eps = 0.9, 0.999, 1e-12
    theta = float(theta0)
    history = []

    for it in range(iters):
        tape = wp.Tape()
        with tape:
            sim.rollout()
            loss_mod.compute(sim.frame_states())
        tape.backward(loss_mod.loss)
        wp.synchronize()
        L = loss_mod.value()
        g = float(sim.wind_strength.grad.numpy()[0])
        tape.zero()

        m = beta1 * m + (1 - beta1) * g
        v = beta2 * v + (1 - beta2) * g * g
        m_hat = m / (1 - beta1 ** (it + 1))
        v_hat = v / (1 - beta2 ** (it + 1))
        theta = theta - lr * m_hat / (np.sqrt(v_hat) + eps)
        sim.set_wind_strength(theta)

        history.append({"iter": it, "theta": theta, "loss": L, "grad": g})
        print(f"  iter {it:3d}  loss={L:.6e}  grad={g:+.3e}  theta={theta:9.4f}")

    return theta, history


def recover_cem(cfg, target, theta0, iters=15, pop=16, sigma0=5.0, seed=42):
    sim = FlagSim(cfg, requires_grad=False)
    loss_mod = TrajectoryLoss(target, requires_grad=False)

    def loss_fn(theta):
        sim.set_wind_strength(theta)
        sim.rollout()
        loss_mod.compute(sim.frame_states())
        return loss_mod.value()

    theta, history = cem_1d(
        loss_fn, mu0=theta0, sigma0=sigma0, pop_size=pop, iters=iters,
        seed=seed, lower=0.0, upper=60.0,
    )
    return theta, history


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(REPO / "configs" / "flag.yaml"))
    ap.add_argument("--solver", default=None)
    ap.add_argument("--method", choices=["grad", "cem"], default="grad")
    ap.add_argument("--theta0", type=float, default=8.0, help="initial guess")
    ap.add_argument("--iters", type=int, default=None)
    args = ap.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    if args.solver:
        cfg["sim"]["solver"] = args.solver
    solver_name = cfg["sim"]["solver"]
    theta_true = float(cfg["wind"]["strength"])
    np.random.seed(cfg["seed"])

    if args.method == "grad" and solver_name == "vbd":
        print("ERROR: tape gradients are zero through SolverVBD (newton 1.4.0); use --method cem")
        return 1

    wp.init()
    assert wp.get_device(cfg["device"]).is_cuda, "requires a GPU"

    with wp.ScopedDevice(cfg["device"]):
        print(f"solver={solver_name}  method={args.method}  theta_true={theta_true}  theta0={args.theta0}")
        print("generating synthetic target ...")
        target = make_target(cfg, theta_true)

        t0 = time.time()
        if args.method == "grad":
            theta_hat, history = recover_grad(cfg, target, args.theta0, iters=args.iters or 40)
            losses = [h["loss"] for h in history]
            thetas = [h["theta"] for h in history]
        else:
            theta_hat, history = recover_cem(cfg, target, args.theta0, iters=args.iters or 15,
                                             seed=cfg["seed"])
            losses = [h["best_loss"] for h in history]
            thetas = [h["mu"] for h in history]
        elapsed = time.time() - t0

    err = abs(theta_hat - theta_true)
    print()
    print(f"theta_true      = {theta_true:.4f}")
    print(f"theta_recovered = {theta_hat:.4f}   (abs err {err:.4f}, {100 * err / theta_true:.2f}%)")
    print(f"wall time: {elapsed:.1f} s")

    out = REPO / "outputs"
    out.mkdir(exist_ok=True)
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    axes[0].semilogy(losses)
    axes[0].set(xlabel="iteration", ylabel="loss", title="loss curve")
    axes[1].plot(thetas, label="recovered")
    axes[1].axhline(theta_true, color="k", ls="--", label=f"theta_true={theta_true}")
    axes[1].set(xlabel="iteration", ylabel="wind strength", title="parameter recovery")
    axes[1].legend()
    fig.suptitle(f"{solver_name} / {args.method}: recovered {theta_hat:.3f} vs true {theta_true}")
    fig.tight_layout()
    png = out / f"recover_{solver_name}_{args.method}.png"
    fig.savefig(png, dpi=120)
    print(f"saved plot: {png}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
