"""i2v bake-off: which model's generated motion is closest to the physical manifold?

For each backend x seed (videos pre-generated by scripts/run_i2v.py):
  LK-track the generated video -> attach tracks to the cloth via I0 barycentrics
  -> multi-start LM projects the motion onto our Newton model family
  -> score = post-fit 2D residual (px RMS), with trackability + motion magnitude.

The video model only sees a static I0, so it CANNOT know theta_true — recovered
theta is reported descriptively (what physics the model implied), NOT as error
vs ground truth. Low fit residual + substantial motion = physically plausible,
usable motion prior. Near-static videos are flagged degenerate (they fit
trivially).

Run in the WARP env (sim side; reads frames from outputs/i2v_*.npz):
  python scripts/run_bakeoff.py --backends wan5b hunyuan --seeds 0 1 2
"""

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import warp as wp  # noqa: E402

from src.optimize.lm import lm_recover  # noqa: E402
from src.render.camera import Camera, project_bary_points_kernel  # noqa: E402
from src.sim.theta_sim import (  # noqa: E402
    THETA_DIM,
    THETA_NAMES,
    ThetaFlagSim,
    theta_natural,
    theta_vec_from_cfg,
)
from src.track.lk import attach_barycentric, track_video  # noqa: E402

FD_H = np.array([0.2, 0.2, 0.2, 0.1, 0.04, 0.04, 0.04, 0.04])
START_SIGMA = np.array([3.0, 2.0, 2.0, 1.0, 0.5, 0.5, 0.5, 0.3])
STATIC_MOTION_FLOOR_PX = 20.0  # median cumulative track motion below this = degenerate


def recover_from_tracks(cfg, tracks, tri_idx, bary, camera, starts, iters, fixed_names):
    """Multi-start LM on 2D pixel residuals. tracks in the camera's pixel space."""
    F, M = tracks.shape[0], tracks.shape[1]
    sim = ThetaFlagSim(cfg, requires_grad=False)
    theta0 = theta_vec_from_cfg(cfg["theta"]["init_values"])
    theta_true = theta_vec_from_cfg(cfg["theta"]["true_values"])

    fixed = [THETA_NAMES.index(n) for n in fixed_names]
    free = [i for i in range(THETA_DIM) if i not in fixed]
    theta0[fixed] = theta_true[fixed]

    track_tri = wp.array(tri_idx, dtype=wp.int32)
    track_bary = wp.array(bary.astype(np.float32), dtype=wp.vec3)
    uv_buf = wp.zeros(int(M), dtype=wp.vec2)
    cam_args = camera.wp_args()
    norm = camera.width * np.sqrt((F - 1) * M)
    tgt_uv = tracks[1:].astype(np.float64)

    def residual_fn(th_free):
        th = theta0.copy()
        th[free] = th_free
        sim.set_theta(th)
        sim.rollout()
        res = np.empty((F - 1, M, 2))
        for f, state in enumerate(sim.frame_states()[1 : F]):
            wp.launch(project_bary_points_kernel, dim=int(M),
                      inputs=[state.particle_q, sim.model.tri_indices,
                              track_tri, track_bary, *cam_args],
                      outputs=[uv_buf])
            res[f] = uv_buf.numpy() - tgt_uv[f]
        return res.ravel() / norm

    rng = np.random.default_rng(cfg["seed"])
    best = (np.inf, None)
    for s in range(starts):
        th_start = theta0[free].copy()
        if s > 0:
            th_start = th_start + rng.normal(0, 1, len(free)) * START_SIGMA[free]
        hat_free, _ = lm_recover(residual_fn, th_start, FD_H[free].copy(),
                                 iters=iters, verbose=False)
        r = residual_fn(hat_free)
        L = float(r @ r) if np.isfinite(r).all() else np.inf
        print(f"    start {s}: loss {L:.6e}")
        if L < best[0]:
            th = theta0.copy()
            th[free] = hat_free
            best = (L, th)
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(REPO / "configs" / "flag.yaml"))
    ap.add_argument("--backends", nargs="+", default=["wan5b", "hunyuan"])
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument("--starts", type=int, default=2)
    ap.add_argument("--iters", type=int, default=20)
    args = ap.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    # retime the sim to the generated video: 24 fps, 48 frames (2.0 s), dt stable
    cfg["sim"]["fps"] = 24
    cfg["sim"]["num_frames"] = 48
    cfg["sim"]["substeps"] = 96  # dt = 4.34e-4 < 5.2e-4 stability envelope
    np.random.seed(cfg["seed"])

    wp.init()
    assert wp.get_device(cfg["device"]).is_cuda

    out = REPO / "outputs"
    results = []

    with wp.ScopedDevice(cfg["device"]):
        # frame-0 geometry for attachment (build state only, no rollout)
        ref = ThetaFlagSim(cfg, requires_grad=False)
        q0 = ref.states[0].particle_q.numpy()
        tris = ref.model.tri_indices.numpy()
        camera = Camera(cfg["m4"]["camera"])
        uv0, depth0 = camera.project(q0)
        del ref

        for backend in args.backends:
            for seed in args.seeds:
                npz = out / f"i2v_{backend}_seed{seed}.npz"
                if not npz.exists():
                    print(f"[skip] {npz.name} missing — generate with run_i2v.py first")
                    continue
                frames = np.load(npz)["frames"]
                F_video = min(frames.shape[0], cfg["sim"]["num_frames"] + 1)
                print(f"\n=== {backend} seed {seed}  ({frames.shape[0]} frames)")

                tracks, valid = track_video(frames)
                scale = camera.width / frames.shape[2]  # video px -> render px
                tracks = tracks * scale
                keep0 = valid[F_video - 1]
                tri_idx, bary, inside = attach_barycentric(tracks[0], uv0, tris, depth0)
                keep = inside & keep0
                M = int(keep.sum())
                surv = 100.0 * keep0.sum() / tracks.shape[1]
                med_motion = np.nanmedian(
                    np.abs(np.diff(tracks[:F_video, keep], axis=0)).sum(axis=(0, 2)))
                print(f"  tracks: {M} on-cloth full-horizon ({surv:.0f}% survival), "
                      f"median motion {med_motion:.0f} px")

                row = {"backend": backend, "seed": seed, "tracks": M,
                       "survival_pct": round(surv, 1), "median_motion_px": round(float(med_motion), 1)}
                if M < 20:
                    row.update({"status": "too_few_tracks"})
                    results.append(row)
                    print("  -> TOO FEW TRACKS, skipping fit")
                    continue

                t0 = time.time()
                L, theta_hat = recover_from_tracks(
                    cfg, tracks[:F_video, keep], tri_idx[keep], bary[keep], camera,
                    args.starts, args.iters, fixed_names=["log_mass"])
                rms_px = float(np.sqrt(L) * camera.width)
                degenerate = med_motion < STATIC_MOTION_FLOOR_PX
                row.update({
                    "status": "degenerate_static" if degenerate else "ok",
                    "fit_rms_px": round(rms_px, 2),
                    "fit_seconds": round(time.time() - t0),
                    "theta_implied": {k: round(v, 3) for k, v in theta_natural(theta_hat).items()},
                })
                results.append(row)
                print(f"  -> fit RMS {rms_px:.2f} px in {row['fit_seconds']} s"
                      f"{'  [DEGENERATE: near-static]' if degenerate else ''}")

    (out / "bakeoff_results.json").write_text(json.dumps(results, indent=2))
    print("\n================ BAKE-OFF SUMMARY ================")
    print(f"{'backend':>9} {'seed':>4} {'tracks':>6} {'surv%':>6} {'motion':>7} {'fitRMSpx':>9}  status")
    for r in results:
        print(f"{r['backend']:>9} {r['seed']:>4} {r['tracks']:>6} {r['survival_pct']:>6} "
              f"{r['median_motion_px']:>7} {r.get('fit_rms_px', float('nan')):>9}  {r.get('status','-')}")
    for backend in args.backends:
        ok = [r for r in results if r["backend"] == backend and r.get("status") == "ok"]
        if ok:
            print(f"{backend}: mean fit RMS {np.mean([r['fit_rms_px'] for r in ok]):.2f} px "
                  f"over {len(ok)} usable videos, mean motion "
                  f"{np.mean([r['median_motion_px'] for r in ok]):.0f} px")
        else:
            print(f"{backend}: no usable (non-degenerate) videos")
    print(f"saved {out / 'bakeoff_results.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
